from . import printers_list
from . import label_template_type
from . import label_template_placeholder
from . import placeholder_path
from . import label_automation_rule
from . import natura_print_service
from . import product_template
from . import res_partner
from . import res_config_settings
from . import res_users
from . import stock_move
from . import stock_lot
from . import stock_quant
from . import mrp_production
from . import mrp_bom
from . import sale_order_line
from . import zpl_label_templates
